version: '3.8'

services:
  mongodb:
    image: mongo:latest #Pulls the latest mongo image from docker hub
    container_name: mongodb
    ports:
      - "27017:27017" #The port on which mongoDB will run is 27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:


